### ISSUE TITLE
Install and configure an operating system of the GNU/Linux family

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-Rudya93#2]
* [x] Install [XUbuntu](https://xubuntu.org/)
* [x] Learn about APT. [Here](https://help.ubuntu.com/lts/serverguide/apt.html.en) and [there](https://help.ubuntu.com/community/AptGet/Howto)
* [ ] Install [Kitty terminal emulator](https://sw.kovidgoyal.net/kitty/binary.html)
* [x] [Install Google Chrome](https://www.linuxbabe.com/ubuntu/install-google-chrome-ubuntu-18-04-lts) but scroll to the section `"Install Google Chrome on Ubuntu 18.04 LTS from the Command Line"` and use it. No GUI-based install, please
* [x] Install [Git from PPA](https://git-scm.com/download/linux)
* [x] Install VS Code using [this instruction](https://code.visualstudio.com/docs/setup/linux#_installation), **but** without downloading `*.deb` file so find the line `"The repository and key can also be installed manually with the following script:"` and go from there

-------------------

P.S. You may try using scripts @RootenberG works on right now, but they may be incomplete: https://github.com/kpi-web-guild/devspace/pull/6

**Comment by Rudya93** [comment]
Start to configure env

**Comment by Rudya93** [comment]
Need help with Kitty, when I try to start, I receive 
 /home/user/.local/kitty.app/bin/kitty
[192 09:57:13.500760] Traceback (most recent call last):
  File "kitty/main.py", line 274, in main
  File "kitty/main.py", line 262, in _main
  File "kitty/main.py", line 89, in init_glfw
RuntimeError: Failed to dlopen /home/user/.local/kitty.app/lib/kitty/kitty/glfw-x11.so with error: libxcb-xkb.so.1: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога

**Comment by Rudya93** [comment]
Install Chrome done

**Comment by Rudya93** [comment]
git installed

**Comment by Rudya93** [comment]
VS Code installed

**Comment by webknjaz** [comment]
You should stop using localized console messages. I have no idea what's the real message in English is and you're going to have a hard time googling that too. At glance,  you did something wrong. You may try reporting this in the issue tracker for Kitty.
